language: python

python:
    - "2.7.12"
    
install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - nosetests api/tests/ --with-coverage

after_success:
- coveralls
